version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.4
jobs:
  build:
    working_directory: ~/Domestic-workers-system-frontend
    docker:
    - image: circleci/node:12.16.1
    steps:
    - checkout
    - run:
        name: update-npm
        command: sudo npm install -g npm@latest
    - restore_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
    - run:
        name: install-npm-dependencies
        command: npm install
    - save_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
        paths:
        - ./node_modules
    - run: npm run test:react
    # - run:
    #     name: code-coverage
    #     command: ./node_modules/.bin/nyc report --reporter=text-lcov
